/**
 * POST /api/techniques/seed — seed database with 12 professional techniques
 * Admin only
 */

import type { NextApiRequest, NextApiResponse } from 'next';
import { getDb } from '@/lib/db/client';
import { COLLECTIONS } from '@/lib/db/constants';
import { requireAdmin } from '@/lib/auth/middleware';
import type { TechniqueDoc } from '@/lib/models';

const SEED_TECHNIQUES: Omit<TechniqueDoc, '_id' | 'createdAt' | 'updatedAt' | 'createdBy'>[] = [
  // 1. OFFENSIVE TECHNIQUES
  {
    techniqueId: 'power-smash',
    name: 'Power Smash',
    category: 'offensive',
    difficulty: 'intermediate',
    description: 'An aggressive overhead shot to finish the point with maximum downward power',
    keyPoints: [
      'Rotate shoulders 90° back during preparation',
      'Jump off dominant foot for maximum power',
      'Contact shuttle at highest point above head',
      'Snap wrist downward sharply on contact',
      'Follow through across body toward opposite hip',
    ],
    poses: [
      {
        name: 'Ready Position',
        description: 'Balanced stance, racket up, weight on balls of feet',
        durationMs: 800,
        joints: {
          head: { x: 200, y: 80, z: 0 },
          neck: { x: 200, y: 110, z: 0 },
          torso: { x: 200, y: 200, z: 0 },
          hips: { x: 200, y: 290, z: 0 },
          leftShoulder: { x: 160, y: 130, z: -10 },
          leftElbow: { x: 140, y: 180, z: -5 },
          leftHand: { x: 130, y: 230, z: 0 },
          rightShoulder: { x: 240, y: 130, z: 10 },
          rightElbow: { x: 260, y: 170, z: 15 },
          rightHand: { x: 270, y: 120, z: 20 },
          racket: { x: 290, y: 80, z: 25 },
          leftHip: { x: 180, y: 290, z: -5 },
          leftKnee: { x: 175, y: 370, z: -8 },
          leftFoot: { x: 170, y: 450, z: -10 },
          rightHip: { x: 220, y: 290, z: 5 },
          rightKnee: { x: 225, y: 370, z: 8 },
          rightFoot: { x: 230, y: 450, z: 10 },
        },
      },
      {
        name: 'Wind-Up',
        description: 'Rotate back, racket behind head, weight shifting to back foot',
        durationMs: 600,
        joints: {
          head: { x: 200, y: 80, z: 0 },
          neck: { x: 200, y: 110, z: 0 },
          torso: { x: 200, y: 200, z: 0 },
          hips: { x: 200, y: 290, z: 0 },
          leftShoulder: { x: 160, y: 130, z: -10 },
          leftElbow: { x: 120, y: 170, z: -15 },
          leftHand: { x: 100, y: 220, z: -20 },
          rightShoulder: { x: 240, y: 130, z: 10 },
          rightElbow: { x: 280, y: 100, z: 30 },
          rightHand: { x: 220, y: 50, z: 40 },
          racket: { x: 200, y: 30, z: 50 },
          leftHip: { x: 180, y: 290, z: -5 },
          leftKnee: { x: 175, y: 360, z: -8 },
          leftFoot: { x: 170, y: 450, z: -10 },
          rightHip: { x: 220, y: 290, z: 5 },
          rightKnee: { x: 235, y: 355, z: 10 },
          rightFoot: { x: 250, y: 440, z: 15 },
        },
      },
      {
        name: 'Contact Point',
        description: 'Full extension, wrist snap, maximum height',
        durationMs: 400,
        joints: {
          head: { x: 200, y: 70, z: 0 },
          neck: { x: 200, y: 100, z: 0 },
          torso: { x: 200, y: 190, z: 0 },
          hips: { x: 200, y: 280, z: 0 },
          leftShoulder: { x: 160, y: 120, z: -10 },
          leftElbow: { x: 130, y: 170, z: -15 },
          leftHand: { x: 110, y: 230, z: -20 },
          rightShoulder: { x: 240, y: 120, z: 10 },
          rightElbow: { x: 270, y: 80, z: 20 },
          rightHand: { x: 280, y: 40, z: 30 },
          racket: { x: 290, y: 10, z: 35 },
          leftHip: { x: 180, y: 280, z: -5 },
          leftKnee: { x: 170, y: 360, z: -10 },
          leftFoot: { x: 160, y: 450, z: -15 },
          rightHip: { x: 220, y: 280, z: 5 },
          rightKnee: { x: 240, y: 340, z: 15 },
          rightFoot: { x: 260, y: 420, z: 20 },
        },
      },
    ],
    tags: ['overhead', 'power', 'finishing', 'jump'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },
  {
    techniqueId: 'deceptive-drop-shot',
    name: 'Deceptive Drop Shot',
    category: 'offensive',
    difficulty: 'advanced',
    description: 'A soft shot that barely clears the net, disguised as a smash to deceive opponent',
    keyPoints: [
      'Use identical wind-up as power smash',
      'Slow down racket head just before contact',
      'Use wrist to guide, not power the shot',
      'Contact shuttle at front of racket strings',
      'Minimal follow-through to maintain deception',
    ],
    poses: [
      {
        name: 'Preparation',
        description: 'Looks identical to smash preparation',
        durationMs: 800,
        joints: {
          head: { x: 200, y: 80, z: 0 },
          neck: { x: 200, y: 110, z: 0 },
          torso: { x: 200, y: 200, z: 0 },
          hips: { x: 200, y: 290, z: 0 },
          leftShoulder: { x: 160, y: 130, z: -10 },
          leftElbow: { x: 120, y: 170, z: -15 },
          leftHand: { x: 100, y: 220, z: -20 },
          rightShoulder: { x: 240, y: 130, z: 10 },
          rightElbow: { x: 280, y: 100, z: 30 },
          rightHand: { x: 220, y: 50, z: 40 },
          racket: { x: 200, y: 30, z: 50 },
          leftHip: { x: 180, y: 290, z: -5 },
          leftKnee: { x: 175, y: 360, z: -8 },
          leftFoot: { x: 170, y: 450, z: -10 },
          rightHip: { x: 220, y: 290, z: 5 },
          rightKnee: { x: 235, y: 355, z: 10 },
          rightFoot: { x: 250, y: 440, z: 15 },
        },
      },
      {
        name: 'Soft Contact',
        description: 'Gentle touch, racket slows down dramatically',
        durationMs: 600,
        joints: {
          head: { x: 200, y: 75, z: 0 },
          neck: { x: 200, y: 105, z: 0 },
          torso: { x: 200, y: 195, z: 0 },
          hips: { x: 200, y: 285, z: 0 },
          leftShoulder: { x: 160, y: 125, z: -10 },
          leftElbow: { x: 135, y: 175, z: -12 },
          leftHand: { x: 120, y: 225, z: -15 },
          rightShoulder: { x: 240, y: 125, z: 10 },
          rightElbow: { x: 265, y: 90, z: 18 },
          rightHand: { x: 275, y: 60, z: 22 },
          racket: { x: 285, y: 40, z: 25 },
          leftHip: { x: 180, y: 285, z: -5 },
          leftKnee: { x: 172, y: 365, z: -8 },
          leftFoot: { x: 165, y: 450, z: -12 },
          rightHip: { x: 220, y: 285, z: 5 },
          rightKnee: { x: 235, y: 350, z: 12 },
          rightFoot: { x: 250, y: 435, z: 18 },
        },
      },
    ],
    tags: ['overhead', 'deception', 'finesse', 'touch'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },
  {
    techniqueId: 'jump-smash',
    name: 'Jump Smash',
    category: 'offensive',
    difficulty: 'advanced',
    description: 'Explosive aerial smash with full body rotation for devastating power',
    keyPoints: [
      'Time jump to meet shuttle at peak height',
      'Drive off dominant leg for maximum elevation',
      'Rotate entire body mid-air for power transfer',
      'Contact at highest point with full arm extension',
      'Land on same foot to maintain balance',
    ],
    poses: [
      {
        name: 'Preparation',
        description: 'Coiled position, ready to explode upward',
        durationMs: 600,
        joints: {
          head: { x: 200, y: 90, z: 0 },
          neck: { x: 200, y: 120, z: 0 },
          torso: { x: 200, y: 210, z: 0 },
          hips: { x: 200, y: 300, z: 0 },
          leftShoulder: { x: 165, y: 140, z: -8 },
          leftElbow: { x: 130, y: 190, z: -12 },
          leftHand: { x: 110, y: 240, z: -18 },
          rightShoulder: { x: 235, y: 140, z: 8 },
          rightElbow: { x: 270, y: 120, z: 25 },
          rightHand: { x: 230, y: 70, z: 35 },
          racket: { x: 210, y: 50, z: 45 },
          leftHip: { x: 185, y: 300, z: -5 },
          leftKnee: { x: 180, y: 380, z: -10 },
          leftFoot: { x: 175, y: 460, z: -15 },
          rightHip: { x: 215, y: 300, z: 5 },
          rightKnee: { x: 220, y: 380, z: 10 },
          rightFoot: { x: 225, y: 460, z: 15 },
        },
      },
      {
        name: 'Airborne Contact',
        description: 'Peak height, full extension, explosive power',
        durationMs: 300,
        joints: {
          head: { x: 200, y: 50, z: 0 },
          neck: { x: 200, y: 80, z: 0 },
          torso: { x: 200, y: 170, z: 0 },
          hips: { x: 200, y: 260, z: 0 },
          leftShoulder: { x: 155, y: 100, z: -12 },
          leftElbow: { x: 120, y: 150, z: -18 },
          leftHand: { x: 100, y: 210, z: -25 },
          rightShoulder: { x: 245, y: 100, z: 12 },
          rightElbow: { x: 280, y: 60, z: 25 },
          rightHand: { x: 290, y: 20, z: 35 },
          racket: { x: 300, y: 0, z: 40 },
          leftHip: { x: 180, y: 260, z: -8 },
          leftKnee: { x: 165, y: 330, z: -15 },
          leftFoot: { x: 150, y: 410, z: -22 },
          rightHip: { x: 220, y: 260, z: 8 },
          rightKnee: { x: 245, y: 310, z: 20 },
          rightFoot: { x: 270, y: 380, z: 28 },
        },
      },
    ],
    tags: ['jump', 'power', 'aerial', 'explosive'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },

  // 2. DEFENSIVE TECHNIQUES
  {
    techniqueId: 'defensive-clear',
    name: 'Defensive Clear',
    category: 'defensive',
    difficulty: 'beginner',
    description: 'High, deep shot to the back of the court to buy recovery time',
    keyPoints: [
      'Get under the shuttle quickly',
      'Contact point high and slightly in front',
      'Use full arm extension for maximum height',
      'Aim for the back baseline',
      'Follow through upward to generate height',
    ],
    poses: [
      {
        name: 'Ready',
        description: 'Defensive stance, racket up',
        durationMs: 700,
        joints: {
          head: { x: 200, y: 85, z: 0 },
          neck: { x: 200, y: 115, z: 0 },
          torso: { x: 200, y: 205, z: 0 },
          hips: { x: 200, y: 295, z: 0 },
          leftShoulder: { x: 165, y: 135, z: -8 },
          leftElbow: { x: 145, y: 185, z: -5 },
          leftHand: { x: 135, y: 235, z: 0 },
          rightShoulder: { x: 235, y: 135, z: 8 },
          rightElbow: { x: 255, y: 175, z: 12 },
          rightHand: { x: 265, y: 125, z: 18 },
          racket: { x: 280, y: 85, z: 22 },
          leftHip: { x: 185, y: 295, z: -5 },
          leftKnee: { x: 180, y: 375, z: -8 },
          leftFoot: { x: 175, y: 455, z: -10 },
          rightHip: { x: 215, y: 295, z: 5 },
          rightKnee: { x: 220, y: 375, z: 8 },
          rightFoot: { x: 225, y: 455, z: 10 },
        },
      },
      {
        name: 'Upward Contact',
        description: 'Full extension upward, sending shuttle high',
        durationMs: 500,
        joints: {
          head: { x: 200, y: 75, z: 0 },
          neck: { x: 200, y: 105, z: 0 },
          torso: { x: 200, y: 195, z: 0 },
          hips: { x: 200, y: 285, z: 0 },
          leftShoulder: { x: 165, y: 125, z: -10 },
          leftElbow: { x: 140, y: 175, z: -12 },
          leftHand: { x: 125, y: 230, z: -15 },
          rightShoulder: { x: 235, y: 125, z: 10 },
          rightElbow: { x: 265, y: 85, z: 18 },
          rightHand: { x: 280, y: 45, z: 25 },
          racket: { x: 290, y: 15, z: 30 },
          leftHip: { x: 185, y: 285, z: -5 },
          leftKnee: { x: 175, y: 365, z: -10 },
          leftFoot: { x: 170, y: 455, z: -15 },
          rightHip: { x: 215, y: 285, z: 5 },
          rightKnee: { x: 230, y: 350, z: 12 },
          rightFoot: { x: 245, y: 430, z: 18 },
        },
      },
    ],
    tags: ['defensive', 'clear', 'recovery', 'high'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },
  {
    techniqueId: 'backhand-block',
    name: 'Backhand Block',
    category: 'defensive',
    difficulty: 'intermediate',
    description: 'Compact backhand defense to return aggressive smashes',
    keyPoints: [
      'Keep racket face angled upward',
      'Minimal backswing for quick reaction',
      'Use wrist to absorb power',
      'Contact in front of body',
      'Guide shuttle to opponent\'s midcourt',
    ],
    poses: [
      {
        name: 'Ready Position',
        description: 'Compact stance, racket ready',
        durationMs: 600,
        joints: {
          head: { x: 200, y: 85, z: 0 },
          neck: { x: 200, y: 115, z: 0 },
          torso: { x: 200, y: 205, z: 0 },
          hips: { x: 200, y: 295, z: 0 },
          leftShoulder: { x: 170, y: 135, z: -8 },
          leftElbow: { x: 155, y: 185, z: -5 },
          leftHand: { x: 145, y: 235, z: 0 },
          rightShoulder: { x: 230, y: 135, z: 8 },
          rightElbow: { x: 210, y: 175, z: 5 },
          rightHand: { x: 190, y: 155, z: 0 },
          racket: { x: 170, y: 135, z: -5 },
          leftHip: { x: 185, y: 295, z: -5 },
          leftKnee: { x: 180, y: 375, z: -8 },
          leftFoot: { x: 175, y: 455, z: -10 },
          rightHip: { x: 215, y: 295, z: 5 },
          rightKnee: { x: 220, y: 375, z: 8 },
          rightFoot: { x: 225, y: 455, z: 10 },
        },
      },
      {
        name: 'Block Contact',
        description: 'Absorb power, guide to midcourt',
        durationMs: 400,
        joints: {
          head: { x: 200, y: 80, z: 0 },
          neck: { x: 200, y: 110, z: 0 },
          torso: { x: 200, y: 200, z: 0 },
          hips: { x: 200, y: 290, z: 0 },
          leftShoulder: { x: 170, y: 130, z: -8 },
          leftElbow: { x: 160, y: 180, z: -6 },
          leftHand: { x: 150, y: 230, z: -2 },
          rightShoulder: { x: 230, y: 130, z: 8 },
          rightElbow: { x: 200, y: 165, z: 2 },
          rightHand: { x: 175, y: 145, z: -3 },
          racket: { x: 155, y: 125, z: -8 },
          leftHip: { x: 185, y: 290, z: -5 },
          leftKnee: { x: 178, y: 370, z: -8 },
          leftFoot: { x: 172, y: 455, z: -12 },
          rightHip: { x: 215, y: 290, z: 5 },
          rightKnee: { x: 222, y: 370, z: 10 },
          rightFoot: { x: 228, y: 455, z: 12 },
        },
      },
    ],
    tags: ['backhand', 'defensive', 'block', 'quick'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },

  // 3. SERVE TECHNIQUES
  {
    techniqueId: 'low-serve',
    name: 'Low Serve',
    category: 'serve',
    difficulty: 'beginner',
    description: 'Controlled serve that barely clears the net and lands in front service court',
    keyPoints: [
      'Hold shuttle by feathers at waist height',
      'Contact below waist level (legal requirement)',
      'Use minimal wrist action for control',
      'Aim for front service line',
      'Follow through toward target',
    ],
    poses: [
      {
        name: 'Setup',
        description: 'Shuttle held, racket back',
        durationMs: 1000,
        joints: {
          head: { x: 200, y: 85, z: 0 },
          neck: { x: 200, y: 115, z: 0 },
          torso: { x: 200, y: 205, z: 0 },
          hips: { x: 200, y: 295, z: 0 },
          leftShoulder: { x: 170, y: 135, z: -8 },
          leftElbow: { x: 155, y: 185, z: -5 },
          leftHand: { x: 145, y: 235, z: 0 },
          rightShoulder: { x: 230, y: 135, z: 8 },
          rightElbow: { x: 250, y: 185, z: 12 },
          rightHand: { x: 265, y: 235, z: 15 },
          racket: { x: 280, y: 255, z: 18 },
          leftHip: { x: 185, y: 295, z: -5 },
          leftKnee: { x: 180, y: 375, z: -8 },
          leftFoot: { x: 175, y: 455, z: -10 },
          rightHip: { x: 215, y: 295, z: 5 },
          rightKnee: { x: 220, y: 375, z: 8 },
          rightFoot: { x: 225, y: 455, z: 10 },
        },
      },
      {
        name: 'Contact',
        description: 'Gentle contact below waist, precise control',
        durationMs: 500,
        joints: {
          head: { x: 200, y: 82, z: 0 },
          neck: { x: 200, y: 112, z: 0 },
          torso: { x: 200, y: 202, z: 0 },
          hips: { x: 200, y: 292, z: 0 },
          leftShoulder: { x: 170, y: 132, z: -8 },
          leftElbow: { x: 160, y: 182, z: -6 },
          leftHand: { x: 155, y: 232, z: -3 },
          rightShoulder: { x: 230, y: 132, z: 8 },
          rightElbow: { x: 240, y: 192, z: 10 },
          rightHand: { x: 245, y: 252, z: 12 },
          racket: { x: 250, y: 272, z: 15 },
          leftHip: { x: 185, y: 292, z: -5 },
          leftKnee: { x: 180, y: 372, z: -8 },
          leftFoot: { x: 175, y: 455, z: -10 },
          rightHip: { x: 215, y: 292, z: 5 },
          rightKnee: { x: 218, y: 372, z: 8 },
          rightFoot: { x: 222, y: 455, z: 10 },
        },
      },
    ],
    tags: ['serve', 'low', 'control', 'precision'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },
  {
    techniqueId: 'flick-serve',
    name: 'Flick Serve',
    category: 'serve',
    difficulty: 'intermediate',
    description: 'Deceptive high serve disguised as a low serve to catch opponent off guard',
    keyPoints: [
      'Setup identical to low serve',
      'Quick wrist flick at last moment',
      'Accelerate racket head suddenly',
      'Aim for rear court or opponent\'s backhand',
      'Use sparingly for maximum surprise effect',
    ],
    poses: [
      {
        name: 'Deceptive Setup',
        description: 'Looks like low serve preparation',
        durationMs: 900,
        joints: {
          head: { x: 200, y: 85, z: 0 },
          neck: { x: 200, y: 115, z: 0 },
          torso: { x: 200, y: 205, z: 0 },
          hips: { x: 200, y: 295, z: 0 },
          leftShoulder: { x: 170, y: 135, z: -8 },
          leftElbow: { x: 155, y: 185, z: -5 },
          leftHand: { x: 145, y: 235, z: 0 },
          rightShoulder: { x: 230, y: 135, z: 8 },
          rightElbow: { x: 250, y: 185, z: 12 },
          rightHand: { x: 265, y: 235, z: 15 },
          racket: { x: 280, y: 255, z: 18 },
          leftHip: { x: 185, y: 295, z: -5 },
          leftKnee: { x: 180, y: 375, z: -8 },
          leftFoot: { x: 175, y: 455, z: -10 },
          rightHip: { x: 215, y: 295, z: 5 },
          rightKnee: { x: 220, y: 375, z: 8 },
          rightFoot: { x: 225, y: 455, z: 10 },
        },
      },
      {
        name: 'Flick Contact',
        description: 'Sudden wrist acceleration, shuttle goes high',
        durationMs: 350,
        joints: {
          head: { x: 200, y: 78, z: 0 },
          neck: { x: 200, y: 108, z: 0 },
          torso: { x: 200, y: 198, z: 0 },
          hips: { x: 200, y: 288, z: 0 },
          leftShoulder: { x: 170, y: 128, z: -8 },
          leftElbow: { x: 165, y: 178, z: -7 },
          leftHand: { x: 162, y: 228, z: -5 },
          rightShoulder: { x: 230, y: 128, z: 8 },
          rightElbow: { x: 235, y: 178, z: 8 },
          rightHand: { x: 235, y: 228, z: 8 },
          racket: { x: 235, y: 248, z: 10 },
          leftHip: { x: 185, y: 288, z: -5 },
          leftKnee: { x: 177, y: 368, z: -10 },
          leftFoot: { x: 172, y: 455, z: -12 },
          rightHip: { x: 215, y: 288, z: 5 },
          rightKnee: { x: 215, y: 368, z: 6 },
          rightFoot: { x: 218, y: 455, z: 8 },
        },
      },
    ],
    tags: ['serve', 'flick', 'deception', 'surprise'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },

  // 4. FOOTWORK TECHNIQUES
  {
    techniqueId: 'split-step',
    name: 'Split Step',
    category: 'footwork',
    difficulty: 'beginner',
    description: 'Explosive ready position that enables quick movement in any direction',
    keyPoints: [
      'Time split as opponent contacts shuttle',
      'Land on balls of both feet simultaneously',
      'Knees bent, weight forward',
      'Ready to push off explosively',
      'Maintain balance and posture',
    ],
    poses: [
      {
        name: 'Pre-Split',
        description: 'Moving forward, anticipating contact',
        durationMs: 400,
        joints: {
          head: { x: 200, y: 80, z: 0 },
          neck: { x: 200, y: 110, z: 0 },
          torso: { x: 200, y: 200, z: 0 },
          hips: { x: 200, y: 290, z: 0 },
          leftShoulder: { x: 165, y: 130, z: -10 },
          leftElbow: { x: 145, y: 180, z: -8 },
          leftHand: { x: 135, y: 230, z: -5 },
          rightShoulder: { x: 235, y: 130, z: 10 },
          rightElbow: { x: 255, y: 170, z: 15 },
          rightHand: { x: 265, y: 120, z: 20 },
          racket: { x: 280, y: 80, z: 25 },
          leftHip: { x: 185, y: 290, z: -5 },
          leftKnee: { x: 182, y: 370, z: -8 },
          leftFoot: { x: 180, y: 450, z: -10 },
          rightHip: { x: 215, y: 290, z: 5 },
          rightKnee: { x: 218, y: 370, z: 8 },
          rightFoot: { x: 220, y: 450, z: 10 },
        },
      },
      {
        name: 'Split Landing',
        description: 'Both feet land, explosive ready position',
        durationMs: 300,
        joints: {
          head: { x: 200, y: 85, z: 0 },
          neck: { x: 200, y: 115, z: 0 },
          torso: { x: 200, y: 205, z: 0 },
          hips: { x: 200, y: 295, z: 0 },
          leftShoulder: { x: 165, y: 135, z: -10 },
          leftElbow: { x: 145, y: 185, z: -8 },
          leftHand: { x: 135, y: 235, z: -5 },
          rightShoulder: { x: 235, y: 135, z: 10 },
          rightElbow: { x: 255, y: 175, z: 15 },
          rightHand: { x: 265, y: 125, z: 20 },
          racket: { x: 280, y: 85, z: 25 },
          leftHip: { x: 180, y: 295, z: -8 },
          leftKnee: { x: 170, y: 380, z: -12 },
          leftFoot: { x: 160, y: 455, z: -15 },
          rightHip: { x: 220, y: 295, z: 8 },
          rightKnee: { x: 230, y: 380, z: 12 },
          rightFoot: { x: 240, y: 455, z: 15 },
        },
      },
    ],
    tags: ['footwork', 'movement', 'ready', 'explosive'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },
  {
    techniqueId: 'lunge-recovery',
    name: 'Lunge and Recovery',
    category: 'footwork',
    difficulty: 'intermediate',
    description: 'Deep lunge to reach front court shots with efficient recovery to center',
    keyPoints: [
      'Drive off back leg powerfully',
      'Extend front leg fully for maximum reach',
      'Keep torso upright and balanced',
      'Push back with front leg immediately',
      'Return to center court position',
    ],
    poses: [
      {
        name: 'Drive Forward',
        description: 'Pushing off back leg toward net',
        durationMs: 400,
        joints: {
          head: { x: 200, y: 85, z: 0 },
          neck: { x: 200, y: 115, z: 0 },
          torso: { x: 200, y: 205, z: 0 },
          hips: { x: 200, y: 295, z: 0 },
          leftShoulder: { x: 165, y: 135, z: -10 },
          leftElbow: { x: 145, y: 185, z: -8 },
          leftHand: { x: 135, y: 235, z: -5 },
          rightShoulder: { x: 235, y: 135, z: 10 },
          rightElbow: { x: 255, y: 175, z: 15 },
          rightHand: { x: 265, y: 125, z: 20 },
          racket: { x: 280, y: 85, z: 25 },
          leftHip: { x: 185, y: 295, z: -5 },
          leftKnee: { x: 180, y: 375, z: -8 },
          leftFoot: { x: 175, y: 455, z: -10 },
          rightHip: { x: 215, y: 295, z: 5 },
          rightKnee: { x: 230, y: 365, z: 10 },
          rightFoot: { x: 245, y: 450, z: 15 },
        },
      },
      {
        name: 'Full Lunge',
        description: 'Maximum extension, front foot planted',
        durationMs: 500,
        joints: {
          head: { x: 200, y: 90, z: 0 },
          neck: { x: 200, y: 120, z: 0 },
          torso: { x: 190, y: 210, z: -5 },
          hips: { x: 185, y: 300, z: -8 },
          leftShoulder: { x: 155, y: 140, z: -15 },
          leftElbow: { x: 135, y: 190, z: -12 },
          leftHand: { x: 125, y: 240, z: -8 },
          rightShoulder: { x: 225, y: 140, z: 5 },
          rightElbow: { x: 245, y: 180, z: 10 },
          rightHand: { x: 255, y: 130, z: 15 },
          racket: { x: 270, y: 90, z: 20 },
          leftHip: { x: 170, y: 300, z: -10 },
          leftKnee: { x: 155, y: 385, z: -15 },
          leftFoot: { x: 140, y: 460, z: -20 },
          rightHip: { x: 200, y: 300, z: -5 },
          rightKnee: { x: 230, y: 360, z: 5 },
          rightFoot: { x: 260, y: 445, z: 12 },
        },
      },
      {
        name: 'Recovery Push',
        description: 'Pushing back toward center',
        durationMs: 600,
        joints: {
          head: { x: 200, y: 82, z: 0 },
          neck: { x: 200, y: 112, z: 0 },
          torso: { x: 195, y: 202, z: -3 },
          hips: { x: 192, y: 292, z: -5 },
          leftShoulder: { x: 160, y: 132, z: -12 },
          leftElbow: { x: 140, y: 182, z: -10 },
          leftHand: { x: 130, y: 232, z: -6 },
          rightShoulder: { x: 230, y: 132, z: 8 },
          rightElbow: { x: 250, y: 172, z: 12 },
          rightHand: { x: 260, y: 122, z: 18 },
          racket: { x: 275, y: 82, z: 22 },
          leftHip: { x: 177, y: 292, z: -8 },
          leftKnee: { x: 165, y: 378, z: -12 },
          leftFoot: { x: 155, y: 458, z: -15 },
          rightHip: { x: 207, y: 292, z: -2 },
          rightKnee: { x: 225, y: 365, z: 8 },
          rightFoot: { x: 245, y: 448, z: 12 },
        },
      },
    ],
    tags: ['footwork', 'lunge', 'recovery', 'movement'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },

  // 5. NET PLAY TECHNIQUES
  {
    techniqueId: 'net-kill',
    name: 'Net Kill',
    category: 'net_play',
    difficulty: 'advanced',
    description: 'Aggressive downward shot at the net to finish the rally',
    keyPoints: [
      'Intercept shuttle as high as possible',
      'Sharp downward angle toward floor',
      'Quick wrist action for speed',
      'Contact in front of body',
      'Aim for opponent\'s feet or sideline',
    ],
    poses: [
      {
        name: 'Reach High',
        description: 'Maximum reach upward at net',
        durationMs: 350,
        joints: {
          head: { x: 200, y: 70, z: 0 },
          neck: { x: 200, y: 100, z: 0 },
          torso: { x: 200, y: 190, z: 0 },
          hips: { x: 200, y: 280, z: 0 },
          leftShoulder: { x: 160, y: 120, z: -10 },
          leftElbow: { x: 135, y: 170, z: -8 },
          leftHand: { x: 120, y: 225, z: -5 },
          rightShoulder: { x: 240, y: 120, z: 10 },
          rightElbow: { x: 265, y: 80, z: 15 },
          rightHand: { x: 280, y: 40, z: 20 },
          racket: { x: 290, y: 10, z: 25 },
          leftHip: { x: 180, y: 280, z: -5 },
          leftKnee: { x: 170, y: 360, z: -10 },
          leftFoot: { x: 160, y: 450, z: -15 },
          rightHip: { x: 220, y: 280, z: 5 },
          rightKnee: { x: 235, y: 345, z: 12 },
          rightFoot: { x: 250, y: 425, z: 18 },
        },
      },
      {
        name: 'Strike Down',
        description: 'Sharp downward angle, explosive wrist',
        durationMs: 250,
        joints: {
          head: { x: 200, y: 75, z: 0 },
          neck: { x: 200, y: 105, z: 0 },
          torso: { x: 200, y: 195, z: 0 },
          hips: { x: 200, y: 285, z: 0 },
          leftShoulder: { x: 162, y: 125, z: -10 },
          leftElbow: { x: 140, y: 175, z: -8 },
          leftHand: { x: 125, y: 230, z: -5 },
          rightShoulder: { x: 238, y: 125, z: 10 },
          rightElbow: { x: 260, y: 95, z: 12 },
          rightHand: { x: 275, y: 75, z: 15 },
          racket: { x: 285, y: 65, z: 18 },
          leftHip: { x: 180, y: 285, z: -5 },
          leftKnee: { x: 168, y: 365, z: -12 },
          leftFoot: { x: 158, y: 452, z: -18 },
          rightHip: { x: 220, y: 285, z: 5 },
          rightKnee: { x: 238, y: 350, z: 15 },
          rightFoot: { x: 255, y: 430, z: 22 },
        },
      },
    ],
    tags: ['net', 'kill', 'aggressive', 'finishing'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },
  {
    techniqueId: 'hairpin-drop',
    name: 'Hairpin Drop',
    category: 'net_play',
    difficulty: 'advanced',
    description: 'Ultra-soft net shot that tumbles just over the net with minimal clearance',
    keyPoints: [
      'Extremely light touch on shuttle',
      'Contact as close to net as possible',
      'Guide shuttle upward barely over net',
      'Shuttle should tumble downward immediately',
      'Practice precision and control',
    ],
    poses: [
      {
        name: 'Close Approach',
        description: 'Get very close to net',
        durationMs: 500,
        joints: {
          head: { x: 200, y: 80, z: 0 },
          neck: { x: 200, y: 110, z: 0 },
          torso: { x: 195, y: 200, z: -3 },
          hips: { x: 192, y: 290, z: -5 },
          leftShoulder: { x: 165, y: 130, z: -10 },
          leftElbow: { x: 145, y: 180, z: -8 },
          leftHand: { x: 135, y: 230, z: -5 },
          rightShoulder: { x: 230, y: 130, z: 8 },
          rightElbow: { x: 245, y: 170, z: 10 },
          rightHand: { x: 255, y: 140, z: 12 },
          racket: { x: 265, y: 120, z: 15 },
          leftHip: { x: 177, y: 290, z: -8 },
          leftKnee: { x: 165, y: 375, z: -12 },
          leftFoot: { x: 155, y: 455, z: -15 },
          rightHip: { x: 207, y: 290, z: -2 },
          rightKnee: { x: 220, y: 370, z: 5 },
          rightFoot: { x: 235, y: 450, z: 10 },
        },
      },
      {
        name: 'Soft Touch',
        description: 'Feather-light contact, minimal power',
        durationMs: 400,
        joints: {
          head: { x: 200, y: 82, z: 0 },
          neck: { x: 200, y: 112, z: 0 },
          torso: { x: 197, y: 202, z: -2 },
          hips: { x: 195, y: 292, z: -4 },
          leftShoulder: { x: 167, y: 132, z: -10 },
          leftElbow: { x: 148, y: 182, z: -8 },
          leftHand: { x: 138, y: 232, z: -5 },
          rightShoulder: { x: 228, y: 132, z: 8 },
          rightElbow: { x: 240, y: 175, z: 8 },
          rightHand: { x: 248, y: 155, z: 10 },
          racket: { x: 255, y: 140, z: 12 },
          leftHip: { x: 180, y: 292, z: -7 },
          leftKnee: { x: 168, y: 377, z: -11 },
          leftFoot: { x: 158, y: 456, z: -14 },
          rightHip: { x: 210, y: 292, z: -1 },
          rightKnee: { x: 223, y: 372, z: 6 },
          rightFoot: { x: 238, y: 451, z: 11 },
        },
      },
    ],
    tags: ['net', 'touch', 'finesse', 'control'],
    viewCount: 0,
    favoriteCount: 0,
    author: 'System',
    isOfficial: true,
    isPublished: true,
  },
];

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', ['POST']);
    return res.status(405).end();
  }

  const admin = await requireAdmin(req, res);
  if (!admin) return;

  const db = getDb();
  const col = db.collection<TechniqueDoc>(COLLECTIONS.TECHNIQUES);

  // Check if already seeded
  const existing = await col.countDocuments();
  if (existing > 0) {
    return res.status(400).json({
      error: 'Database already contains techniques. Delete all techniques first to re-seed.',
      existingCount: existing,
    });
  }

  // Insert all seed techniques
  const docs = SEED_TECHNIQUES.map(tech => ({
    ...tech,
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: admin.username,
  }));

  const result = await col.insertMany(docs);

  return res.status(201).json({
    success: true,
    inserted: result.insertedCount,
    message: `Successfully seeded ${result.insertedCount} professional techniques`,
  });
}
